version: "3.9"

services:

# Backend---------------------------->
  backend:
    build:
      context: ./server
      target: development

    container_name: flipkart-backend

    ports:
      - "5000:5000"

    env_file:
      - ./server/.env

    environment:
      NODE_ENV: development

    volumes:
      - ./server:/app
      - /app/node_modules

    restart: unless-stopped


# Client---------------------------->
  client:
    build:
      context: ./client
      target: development

    container_name: flipkart-client

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000

    volumes:
      - ./client:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped


# Admin------------------------>
  admin:
    build:
      context: ./admin
      target: development

    container_name: flipkart-admin

    ports:
      - "5174:5174"

    environment:
      VITE_API_URL: http://localhost:5000

    volumes:
      - ./admin:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped